version: '3'
services:
  mongo:
    image: mongo:3.4
    container_name: pokedex_db
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
  pokedex:
    build: .
    ports:
      - 8080:8080
volumes:
  db:
